#bag path dir
bag_path : [/mnt/data-2/map_data/6ring_0328_0615/6/testsubmap, /mnt/data-1/map_data/20190613/sensor_20190613-135210_/testsubmap]
# bag_path : [/mnt/data-2/map_data/6ring_0328_0615/3/testreindex]
# , /mnt/data-2/map_data/6ring_0328_0615/6,
# /mnt/data-2/map_data/20190618/sensor_20190618-122836_, /mnt/data-1/map_data/20190613/sensor_20190613-135210_,
# /mnt/data-1/map_data/20190613/sensor_20190613-135210_, /mnt/data-2/map_data/20190619/sensor_20190619-131031_]

#output file name prefix
name_this_turn : navnet_pose_optimize

#lidar odom file which read from bag file
lidar_odom_file_name : _raw_odom_.txt

#lidar odom file which in world frame
#TODO:
lidar_odom_in_world_file_name : _raw_odom_.txt
#lidar_odom_in_world_file_name : _ICPAtAllVertex_.txt

#final lidar odom file which will be write to bag file
final_lidar_odom : _ICPAtAllVertex_.txt

#gnss odom file which read from bag
gnss_odom_file_name : _gnss_odom_.txt

#good gnss odom file which select based on gnss_odom_covariance_threshold
gnss_odom_file_name_good : _gnss_odom_good.txt

#output file dir
out_dir : /mnt/data-1/map_data/6ring_prob1/cut2_1646ddd

#frame file subdir
frame_prefix : frame/
#g2o file subdir
g2o_prefix : g2o/
#map file subdir, not be used now.
map_prefix : map/
#TODO:
loop_detection_max_dis : 20.0
loop_detection_min_dis : 0.0

min_frames_num_of_loop : 40

local_icp_max_dis : 5
global_icp_max_dis : 10

local_icp_max_score : 2
#TODO:
global_icp_max_score : 10 # change from 5
#TODO:
local_icp_edges_num : 1 # change from 5
global_icp_edges_num : 3

gnss_edges_num : 1

icp_max_iters : 50
local_icp_max_correspondence_dis : 5
global_icp_max_correspondence_dis : 10

#submap size
size_of_submap : 1

#lidar to gnss param
gnss_to_lidar_x : 1.17100086441907
gnss_to_lidar_y : -0.1630065904672196
gnss_to_lidar_z : 0.01058459040568946

#using radian from 2018-11-19
gnss_to_lidar_roll : -3.129042033180273
gnss_to_lidar_pitch : 3.119029983253778
gnss_to_lidar_yaw : 1.586142764025011

lidar_name: velodyne
pointcloud_topic : /sensor/velodyne/points
#TODO:
lidar_odom_topic : /sensor/velodyne/odom_correct_00_n155_true
gnss_odom_topic : /sensor/novatel/odom_correct
vehicle_status_topic : /vehicle/status
#TODO:
final_lidar_odom_topic : /pose_optimize/velodyne/odom/fusion_submap_1026_all

#the covariance matrix main symmetric axis's threshold
gnss_odom_covariance_threshold :
- 2
- 2
- 10
- 2
- 2
- 2

#whether do local registration on poseGraphUsingICPAtAllVertex
#TODO:
poseGraphUsingICPAtAllVertex_local_regis_switch : false
#TODO:
#The pose between fix_od_st_time and fix_od_end_time will be fixed
fix_od_st_time: 0
fix_od_end_time: 0

#execute read data from bag
#TODO:
exe_read_data_from_bag : true
#execute pose graph using gnss odom
#TODO:
exe_pose_graph_using_gnss : false
#execute pose graph using icp at all vertex
exe_pose_graph_using_icp_at_all_vertex : true
#execute write pose to bag
#TODO:
exe_write_pose_to_bag : true

x_cov_factor: 0.1
y_cov_factor: 0.1
z_cov_factor: 0.05 #0.001
r_cov_factor: 300
#TODO:
num_threads: 20
fix_stamps: [1551942816.38, 1551942821.29, 1552290983.63, 1552290988.64, 1557987752.87,
1557987756.87, 1558078129.57, 1558078134.93, 1560238431.05, 1560238436.05]